### ISSUE TITLE
How to change GPU

### ISSUE THREAD

**Issue by danboshuiyan** [ohuelab/Solubility_AfDesign#2]
Your work is very meaningful， which I am very interested in. When I was using it, I found that my GPU0 card did not have enough memory. I want to replace it with 1 card. Where should I modify it?
Thanks for your reply

**Comment by blacktanktop** [comment]
I honestly don't know much about the GPU replace.
Since JAX is basically being used, I assume it is an issue regarding the use of GPUs in JAX.

The following JAX issue may be helpful (it talks about the use of multiple GPUs)
https://github.com/google/jax/issues/9859

**Comment by danboshuiyan** [comment]
> I honestly don't know much about the GPU replace. Since JAX is basically being used, I assume it is an issue regarding the use of GPUs in JAX.
> 
> The following JAX issue may be helpful (it talks about the use of multiple GPUs) [google/jax#9859](https://github.com/google/jax/issues/9859)

Thanks for your reply, I use another computer to make it.
If I want to appoint the residue which the protein created can dock, do I need to modify something to make it?

**Comment by blacktanktop** [comment]
maybe you can use hotspot option. (but Sorry, I have not checked the behavior. It is no different than the original AfDesign (from about late 2022-02).)

The actual code is as follows, so try it as the JAX code, as in the example, in a format that is acceptable, even if you insert it in the "H" part
https://github.com/ohuelab/Solubility_AfDesign#for-binder-hallucination-can-i-specify-the-site-i-want-to-bind
https://github.com/ohuelab/Solubility_AfDesign/blob/63de5298822f572875abcb1ee9855c5ad65462b9/design.py#L223-L230
